name: Production deploy 

on:
  release:
    types:
      - published
  
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Echo version
        run: |
          echo  ${{ steps.get_version.outputs.VERSION }}
        
